import os
import sys
from agents.final4 import run_final4_processing
from agents.next_agent import run_next_agent_processing
from utils.text_to_pdf_converter import convert_text_to_pdf

def main():
    """
    Main function to orchestrate the automated resume generation workflow.
    This script assumes that the necessary input files have been generated,
    for instance, by running the streamlit_app.py interface.
    """
    print("🚀 Starting the resume generation pipeline...")

    # Define the paths to the input files generated by the Streamlit app
    current_dir = os.path.dirname(os.path.abspath(__file__))
    job_description_file = os.path.join('data', 'description.txt')
    company_file = os.path.join('data', 'company.txt')
    github_profile_file = os.path.join('data', 'refined_output_github_llm.txt')
    candidate_cv_file = os.path.join('data', 'Piyush_resume_Aug.txt') # Assuming this is the cv file

    # Check if all required input files exist
    required_files = [job_description_file, company_file, github_profile_file, candidate_cv_file]
    missing_files = [f for f in required_files if not os.path.exists(f)]

    if missing_files:
        print("\n❌ Error: The following input files are missing:")
        for f in missing_files:
            print(f"- {f}")
        print("\nPlease run the Streamlit app first to generate these files.")
        sys.exit(1)

    # Step 1: Run the initial analysis using final4.py
    print("\nStep 1: Running Initial Analysis...")
    final4_outputs = run_final4_processing(
        job_description_file=job_description_file,
        company_file=company_file,
        github_profile_file=github_profile_file,
        candidate_cv_file=candidate_cv_file
    )

    if not final4_outputs:
        print("\n❌ Error: Initial analysis (final4.py) failed. Exiting.")
        sys.exit(1)

    print("✅ Step 1 completed successfully.")

    # Step 2: Run the resume refinement loop using next_agent.py
    print("\nStep 2: Running Resume Refinement Loop...")
    final_resume_file = run_next_agent_processing(final4_outputs)

    if not final_resume_file:
        print("\n❌ Error: Resume refinement (next_agent.py) failed. Exiting.")
        sys.exit(1)

    print(f"✅ Step 2 completed successfully. Final resume at: {final_resume_file}")

    # Step 3: Convert the final resume to PDF
    print("\nStep 3: Converting Final Resume to PDF...")
    pdf_path = convert_text_to_pdf(input_text_file=final_resume_file)

    if not pdf_path:
        print("\n❌ Error: PDF conversion failed. Exiting.")
        sys.exit(1)

    print(f"✅ Step 3 completed successfully. PDF generated at: {pdf_path}")
    print("\n🎉 Resume generation pipeline finished successfully!")

if __name__ == '__main__':
    main()